### ISSUE TITLE
Unable to scroll in Firefox

### ISSUE THREAD

**Issue by miketaylr** [GoogleChrome/confluence#160]
STR:

In Firefox 57,
1) open http://web-confluence.appspot.com/#!/confluence
2) attempt to scroll down to see Edge graphs, etc.

I didn't dig in deeply to understand why... but there's an `overflow: hidden` rule on body:

```css
/* Sticky Footer */
      body {
        display: flex;
        flex-direction: column;
        height: 100vh;
        width: 100vw;
	overflow: hidden;
      }
```
